### ISSUE TITLE
run.py failing with the new config changes introduced in af6a5a6

### ISSUE THREAD

**Issue by scabaa** [jordanmalecki/onemap#4]
Not sure if I am doing something wrong but for me with the new config changes the run.py script keeps failing with the following:

`Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from src.augment_rides import augment_rides
  File "./src/augment_rides.py", line 4, in <module>
    from config import HEADERS, COOKIES
ImportError: cannot import name 'HEADERS' from 'config' (./config.py)`

Just FYI as I see the HEADERS and COOKIES are defined under the exaple_config in config.py and I cannot see anything reading that (eg. calling load_config).

Also I think since the config.json is existing and ONEMAP_LOCATION/ONEMAP_MAX_DISTANCE/ONEMAP_NICKNAME is defined there already I assume at the first run it won't be asked for.

But on the positive side your changes to the augment_rides are amazing (tested separately). With 90+ rides it always took a long time to rerun previously so now it's literally a few seconds to rerun.

**Comment by jordanmalecki** [comment]
This error occurs because HEADERS and COOKIES are no longer available as direct imports from config.py. Instead, they are part of the configuration dictionary loaded using the load_config function.

The issue should be fixed in [commit `b852423`](https://github.com/jordanmalecki/onemap/commit/b852423b5f7a516aff0643660fae4041ceb04d66).

...which updated the code to load `HEADERS` and `COOKIES` dynamically from `config.json` using `load_config`, instead of importing them directly. This should prevent the import error you were seeing.

Please check if the changes resolve the problem on your end. If it’s all good, you can close the issue, or just let me know and I'll close it for you.

Thanks fren!

**Comment by scabaa** [comment]
Hey, good news is that I am not getting error on the headers/cookies part so that's been fixed and I am excited to see/test all your other changes.
Unfortunately with those changes you introduced some minor bugs but I will open another issue about those :)
Thanks a lot for your continuous  work on this!
